services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: iubip-hub-frontend:latest
    container_name: iubip-hub-frontend
    network_mode: "host"
    environment:
      NODE_ENV: production
      API_BASE_URL: http://localhost:8000/api
    restart: unless-stopped
