services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: iubip-hub-frontend:latest
    container_name: iubip-hub-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
