# Generated by Django 6.0.5 on 2026-05-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_add_missing_columns'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'managed': False, 'verbose_name': 'Ссылка на документ', 'verbose_name_plural': 'Ссылки на документы (Google Drive, Dropbox и т.д.)'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False, 'verbose_name': 'Роль в проекте', 'verbose_name_plural': 'Роли в проектах (добавляются внутри Проекта)'},
        ),
        migrations.AlterModelOptions(
            name='siterole',
            options={'managed': False, 'verbose_name': 'Уровень доступа', 'verbose_name_plural': 'Уровни доступа (кто может заходить в админку)'},
        ),
        migrations.AlterModelOptions(
            name='studentprojectrole',
            options={'managed': False, 'ordering': ['id', 'student__surname', 'student__name'], 'verbose_name': 'Участник проекта'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'managed': False, 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории (типы проектов/достижений)'},
        ),
    ]
