# Generated by Django 6.0.5 on 2026-05-27 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_hubmanager_alter_hubleader_options_hubleader_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Дизайнер, Разработчик, Проектный менеджер, Тестировщик', max_length=50, verbose_name='Название роли')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_roles', to='hub.laboratory', verbose_name='Лаборатория')),
            ],
            options={
                'verbose_name': 'Роль лаборатории',
                'verbose_name_plural': 'Роли лаборатории',
                'db_table': 'hub_lab_roles',
                'managed': True,
                'unique_together': {('laboratory', 'title')},
            },
        ),
    ]
