# Generated by Django 6.0.5 on 2026-05-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_site_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='stats',
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Например: "48 участников"', max_length=200, verbose_name='Текст статистики')),
                ('icon', models.CharField(help_text='Например: /images/ui/icoHumans.svg', max_length=500, verbose_name='Путь к иконке')),
                ('icon_class', models.CharField(blank=True, default='', help_text='Позиционирование иконки', max_length=500, verbose_name='CSS-классы для иконки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('site_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='hub.sitecontent')),
            ],
            options={
                'verbose_name': 'Элемент статистики',
                'verbose_name_plural': 'Элементы статистики',
                'db_table': 'hub_site_stats',
                'ordering': ['order'],
                'managed': True,
            },
        ),
    ]
