# Generated by Django 6.0.6 on 2026-06-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0020_drop_sitestat_icon_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleManagerFlag',
            fields=[
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manager_flag', serialize=False, to='hub.role', verbose_name='Роль')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Флаг менеджера',
                'verbose_name_plural': 'Флаги менеджеров',
                'db_table': 'hub_role_manager_flags',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='laboratoryimage',
            options={'managed': True, 'verbose_name': 'Изображение лаборатории', 'verbose_name_plural': 'Изображения лабораторий'},
        ),
        migrations.AlterField(
            model_name='hubleader',
            name='degree',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='hubleader',
            name='position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Короткая информация'),
        ),
        migrations.AlterField(
            model_name='hubleader',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_leader_profile', to='hub.user'),
        ),
        migrations.AlterField(
            model_name='laboratoryguide',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_links', to='hub.guide', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='labphoto',
            name='card_image',
            field=models.ImageField(upload_to='labs/', verbose_name='Фото карточки'),
        ),
    ]
