# Generated by Django 6.0.5 on 2026-05-17 18:17

import django.core.validators
import django.db.models.deletion
import hub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_limited', models.CharField(blank=True, db_column='text_limited', max_length=350, null=True, validators=[django.core.validators.MaxLengthValidator(350)], verbose_name='Описание (350 симв.)')),
                ('link', models.URLField(blank=True, max_length=2048, null=True, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/', validators=[hub.models.validate_image_4x3], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'db_table': 'achievements',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'db_table': 'directions',
                'ordering': ['title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=2048, verbose_name='Ссылка на файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Файл достижения',
                'verbose_name_plural': 'Файлы достижений',
                'db_table': 'file_achievements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Файл руководителя',
                'verbose_name_plural': 'Файлы руководителей',
                'db_table': 'file_guide',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Файл проекта',
                'verbose_name_plural': 'Файлы проектов',
                'db_table': 'file_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Файл отчёта',
                'verbose_name_plural': 'Файлы отчётов',
                'db_table': 'file_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
                'db_table': 'guide',
                'ordering': ['surname', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('link', models.URLField(blank=True, max_length=50, null=True, verbose_name='Ссылка на чат')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Активна')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Фотографии (JSON массив)')),
                ('short_description', models.CharField(blank=True, max_length=350, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Лаборатория',
                'verbose_name_plural': 'Лаборатории',
                'db_table': 'laboratories',
                'ordering': ['title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratoryDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на чат')),
            ],
            options={
                'verbose_name': 'Направление лаборатории',
                'verbose_name_plural': 'Направления лабораторий',
                'db_table': 'laboratory_direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratoryLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Лидер лаборатории',
                'verbose_name_plural': 'Лидеры лабораторий',
                'db_table': 'laboratory_leaders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Описание')),
                ('goal', models.CharField(blank=True, db_column='goal', max_length=350, null=True, validators=[django.core.validators.MaxLengthValidator(350)], verbose_name='Цель проекта')),
                ('need_report', models.BooleanField(default=False, verbose_name='Требуется отчёт')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
                'ordering': ['title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLaboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Проект-лаборатория',
                'verbose_name_plural': 'Проекты-лаборатории',
                'db_table': 'project_laboratory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Позиция в проекте',
                'verbose_name_plural': 'Позиции в проектах',
                'db_table': 'project_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('report_text', models.TextField(blank=True, null=True, verbose_name='Текст отчёта')),
                ('confirmation', models.BooleanField(default=False, verbose_name='Подтверждён')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'db_table': 'report',
                'ordering': ['-date_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль проекта',
                'verbose_name_plural': 'Роли проектов',
                'db_table': 'roles',
                'ordering': ['title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль сайта',
                'verbose_name_plural': 'Роли сайта',
                'db_table': 'site_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('study_group', models.CharField(max_length=50, verbose_name='Учебная группа')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('university_city', models.CharField(default='Ростов-на-Дону', max_length=50, verbose_name='Город университета')),
                ('task_board', models.CharField(blank=True, max_length=15, null=True, verbose_name='Task-борд')),
                ('telegram_nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('experience', models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет'), ('Немного', 'Немного')], max_length=7, null=True, verbose_name='Опыт')),
                ('wishes', models.TextField(blank=True, null=True, verbose_name='Пожелания')),
                ('metaverse_account_link', models.URLField(blank=True, max_length=2048, null=True, verbose_name='Ссылка на аккаунт в метавселенной')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'db_table': 'students',
                'ordering': ['surname', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Студент-направление',
                'verbose_name_plural': 'Студенты-направления',
                'db_table': 'student_direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentLaboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Студент-лаборатория',
                'verbose_name_plural': 'Студенты-лаборатории',
                'db_table': 'students_laboratory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True, verbose_name='Действующий участник')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проектов',
                'db_table': 'student_project_roles',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'db_table': 'type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Пользователь админки',
                'verbose_name_plural': 'Пользователи админки',
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='EventLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('user_login', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пользователь')),
                        ('action', models.CharField(choices=[('project_created', 'Создан проект'), ('project_updated', 'Обновлен проект'), ('lab_created', 'Создана лаборатория'), ('lab_updated', 'Обновлена лаборатория'), ('participant_left', 'Участник покинул проект'), ('participant_joined', 'Участник присоединился'), ('report_created', 'Создан отчёт'), ('report_confirmed', 'Отчёт подтверждён')], max_length=50, verbose_name='Действие')),
                        ('entity_type', models.CharField(max_length=50, verbose_name='Тип сущности')),
                        ('entity_id', models.IntegerField(verbose_name='ID сущности')),
                        ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                        ('details', models.TextField(blank=True, null=True, verbose_name='Детали (JSON)')),
                    ],
                    options={
                        'verbose_name': 'Событие',
                        'verbose_name_plural': 'Журнал событий',
                        'db_table': 'event_log',
                        'ordering': ['-timestamp'],
                        'managed': True,
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS `event_log` (
                            `id` bigint NOT NULL AUTO_INCREMENT,
                            `user_login` varchar(50) DEFAULT NULL,
                            `action` varchar(50) NOT NULL,
                            `entity_type` varchar(50) NOT NULL,
                            `entity_id` int NOT NULL,
                            `timestamp` datetime(6) NOT NULL,
                            `details` longtext DEFAULT NULL,
                            PRIMARY KEY (`id`)
                        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='HubLeader',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                        ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                        ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='hub_leader_profile', to='hub.user')),
                    ],
                    options={
                        'verbose_name': 'Руководитель хаба',
                        'verbose_name_plural': 'Руководители хаба',
                        'db_table': 'hub_leaders',
                        'ordering': ['user__login'],
                        'managed': True,
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS `hub_leaders` (
                            `id` bigint NOT NULL AUTO_INCREMENT,
                            `position` varchar(200) NOT NULL,
                            `is_active` tinyint(1) NOT NULL,
                            `created_at` datetime(6) NOT NULL,
                            `user_id` bigint NOT NULL,
                            PRIMARY KEY (`id`),
                            UNIQUE KEY `user_id` (`user_id`)
                        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
