# Generated by Django 6.0.5 on 2026-05-16 19:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubsettings',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='direction',
        ),
        migrations.AddField(
            model_name='lab',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='labs_multi', to='hub.direction', verbose_name='Направления'),
        ),
        migrations.AddField(
            model_name='lab',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='lab',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='Фотографии (JSON массив ссылок)'),
        ),
        migrations.AddField(
            model_name='lab',
            name='short_description',
            field=models.CharField(blank=True, max_length=350, validators=[django.core.validators.MaxLengthValidator(350)], verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(350)], verbose_name='Цель проекта'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(350)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Изображение (4:3, до 2МБ)'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='action',
            field=models.CharField(choices=[('file_download', 'Скачивание файла'), ('report_export', 'Экспорт отчета'), ('participant_left', 'Участник покинул проект'), ('participant_joined', 'Участник присоединился'), ('project_created', 'Создан проект'), ('project_updated', 'Обновлен проект'), ('lab_created', 'Создана лаборатория'), ('lab_updated', 'Обновлена лаборатория'), ('role_changed', 'Изменена роль пользователя'), ('hub_leader_added', 'Добавлен руководитель хаба'), ('hub_leader_removed', 'Удален руководитель хаба')], max_length=50, verbose_name='Действие'),
        ),
        migrations.CreateModel(
            name='HubLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hub_leader_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Руководитель хаба',
                'verbose_name_plural': 'Руководители хаба',
                'ordering': ['user__username'],
            },
        ),
    ]
