# Generated by Django 6.0.5 on 2026-05-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=2048, verbose_name='Ссылка на файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Файл достижения',
                'verbose_name_plural': 'Файлы достижений',
                'db_table': 'file_achievements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Файл руководителя',
                'verbose_name_plural': 'Файлы руководителей',
                'db_table': 'file_guide',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Файл проекта',
                'verbose_name_plural': 'Файлы проектов',
                'db_table': 'file_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Файл отчёта',
                'verbose_name_plural': 'Файлы отчётов',
                'db_table': 'file_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
                'db_table': 'guide',
                'ordering': ['surname', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('link', models.URLField(blank=True, max_length=50, null=True, verbose_name='Ссылка на чат')),
            ],
            options={
                'verbose_name': 'Лаборатория',
                'verbose_name_plural': 'Лаборатории',
                'db_table': 'laboratories',
                'ordering': ['title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratoryDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на чат')),
            ],
            options={
                'verbose_name': 'Направление лаборатории',
                'verbose_name_plural': 'Направления лабораторий',
                'db_table': 'laboratory_direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratoryLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Лидер лаборатории',
                'verbose_name_plural': 'Лидеры лабораторий',
                'db_table': 'laboratory_leaders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLaboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Проект-лаборатория',
                'verbose_name_plural': 'Проекты-лаборатории',
                'db_table': 'project_laboratory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Позиция в проекте',
                'verbose_name_plural': 'Позиции в проектах',
                'db_table': 'project_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('report_text', models.TextField(blank=True, null=True, verbose_name='Текст отчёта')),
                ('confirmation', models.BooleanField(default=False, verbose_name='Подтверждён')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'db_table': 'report',
                'ordering': ['-date_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль проекта',
                'verbose_name_plural': 'Роли проектов',
                'db_table': 'roles',
                'ordering': ['title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль сайта',
                'verbose_name_plural': 'Роли сайта',
                'db_table': 'site_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('study_group', models.CharField(max_length=50, verbose_name='Учебная группа')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('university_city', models.CharField(default='Ростов-на-Дону', max_length=50, verbose_name='Город университета')),
                ('task_board', models.CharField(blank=True, max_length=15, null=True, verbose_name='Task-борд')),
                ('telegram_nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('experience', models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет'), ('Немного', 'Немного')], max_length=7, null=True, verbose_name='Опыт')),
                ('wishes', models.TextField(blank=True, null=True, verbose_name='Пожелания')),
                ('metaverse_account_link', models.URLField(blank=True, max_length=2048, null=True, verbose_name='Ссылка на аккаунт в метавселенной')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'db_table': 'students',
                'ordering': ['surname', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Студент-направление',
                'verbose_name_plural': 'Студенты-направления',
                'db_table': 'student_direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentLaboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Студент-лаборатория',
                'verbose_name_plural': 'Студенты-лаборатории',
                'db_table': 'students_laboratory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True, verbose_name='Действующий участник')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проектов',
                'db_table': 'student_project_roles',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'db_table': 'type',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='HubSettings',
        ),
        migrations.AlterUniqueTogether(
            name='projectparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projectparticipant',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectparticipant',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'managed': False, 'ordering': ['-id'], 'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'managed': False, 'ordering': ['title'], 'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='eventlog',
            options={'managed': True, 'ordering': ['-timestamp'], 'verbose_name': 'Событие', 'verbose_name_plural': 'Журнал событий'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False, 'ordering': ['title'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'Пользователь админки', 'verbose_name_plural': 'Пользователи админки'},
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='user',
        ),
        migrations.AddField(
            model_name='eventlog',
            name='user_login',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='action',
            field=models.CharField(choices=[('project_created', 'Создан проект'), ('project_updated', 'Обновлен проект'), ('lab_created', 'Создана лаборатория'), ('lab_updated', 'Обновлена лаборатория'), ('participant_left', 'Участник покинул проект'), ('participant_joined', 'Участник присоединился'), ('report_created', 'Создан отчёт'), ('report_confirmed', 'Отчёт подтверждён')], max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Детали (JSON)'),
        ),
        migrations.AlterModelTable(
            name='eventlog',
            table='event_log',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.DeleteModel(
            name='ProjectParticipant',
        ),
    ]
