# Generated by Django 6.0.5 on 2026-05-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_delete_status_alter_file_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='managers/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Руководитель хаба',
                'verbose_name_plural': 'Руководители хаба',
                'db_table': 'hub_managers',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='hubleader',
            options={'managed': True, 'ordering': ['full_name'], 'verbose_name': 'Руководитель хаба', 'verbose_name_plural': 'Руководители хаба'},
        ),
        migrations.AddField(
            model_name='hubleader',
            name='degree',
            field=models.CharField(blank=True, max_length=200, verbose_name='Учёная степень / звание'),
        ),
        migrations.AddField(
            model_name='hubleader',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='hubleader',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='hubleader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hub_leaders/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='hubleader',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
