# Generated by Django 6.0.5 on 2026-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_labrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Текст ссылки')),
                ('url', models.URLField(max_length=2048, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Ссылка проекта',
                'verbose_name_plural': 'Ссылки проекта',
                'db_table': 'project_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='О ХАБЕ', max_length=200, verbose_name='Заголовок раздела "О хабе"')),
                ('about_intro', models.TextField(default='Хаб — это экосистема студенческих лабораторий', verbose_name='Текст "О хабе" (первая карточка)')),
                ('about_mission', models.TextField(default='Мы объединяем студентов...', verbose_name='Текст миссии (вторая карточка)')),
                ('labs_subtitle', models.TextField(default='Каждая лаборатория — это команда и своя экспертиза. Выбери направление по душе.', verbose_name='Подзаголовок раздела лабораторий')),
                ('hero_subtitle', models.TextField(default='Открытая площадка для студенческих лабораторий.', verbose_name='Подзаголовок героя')),
                ('hero_description', models.TextField(default='Исследуй, создавай, достигай вместе с нами!', verbose_name='Описание героя (жирная часть)')),
                ('stats', models.JSONField(blank=True, default=list, verbose_name='Элементы статистики (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройка главной страницы',
                'verbose_name_plural': 'Настройки главной страницы',
                'db_table': 'hub_site_content',
                'managed': True,
            },
        ),
    ]
