# Generated by Django 6.0.5 on 2026-05-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_site_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500, verbose_name='Ссылка на изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('laboratory', models.ForeignKey(db_column='laboratory_id', on_delete=django.db.models.deletion.CASCADE, related_name='lab_images', to='hub.laboratory')),
            ],
            options={
                'verbose_name': 'Фотография лаборатории',
                'verbose_name_plural': 'Фотографии лаборатории',
                'db_table': 'hub_lab_images',
                'ordering': ['order'],
                'managed': True,
            },
        ),
    ]
