# Generated by Django 6.0.5 on 2026-05-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_laboratoryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaboratoryImage',
        ),
    ]
